apiVersion: v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: tiffanyjachja/apps_repo:sample-app
        ports:
        - containerPort: 5000