name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs Pytest 
      - uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: pip3 install -r requirements.txt && pytest

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: tiffanyjachja/apps_repo:sample-app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set K8s Context
        uses: azure/k8s-actions/k8s-set-context@master
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            deployment.yaml
            service.yaml
          images: 'tiffanyjachja/apps_repo:sample-app'
          kubectl-version: 'latest'
      


